
const countries = [
    { name: "Afghanistan", code: "AF", phone: 93, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/23px-Flag_of_the_Taliban.svg.png" },
    { name: "Albania", code: "AL", phone: 355, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/21px-Flag_of_Albania.svg.png" },
    { name: "Algeria", code: "DZ", phone: 213, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/23px-Flag_of_Algeria.svg.png" },
    { name: "Andorra", code: "AD", phone: 376, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/22px-Flag_of_Andorra.svg.png" },
    { name: "Angola", code: "AO", phone: 244, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/23px-Flag_of_Angola.svg.png" },
    { name: "Antigua and Barbuda", code: "AG", phone: 1268, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/23px-Flag_of_Antigua_and_Barbuda.svg.png" },
    { name: "Argentina", code: "AR", phone: 54, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.png" },
    { name: "Armenia", code: "AM", phone: 374, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/23px-Flag_of_Armenia.svg.png" },
    { name: "Australia", code: "AU", phone: 61, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/23px-Flag_of_Australia_%28converted%29.svg.png" },
    { name: "Austria", code: "AT", phone: 43, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/23px-Flag_of_Austria.svg.png" },
    { name: "Azerbaijan", code: "AZ", phone: 994, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/23px-Flag_of_Azerbaijan.svg.png" },
    { name: "Bahamas", code: "BS", phone: 1242, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/23px-Flag_of_the_Bahamas.svg.png" },
    { name: "Bahrain", code: "BH", phone: 973, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/23px-Flag_of_Bahrain.svg.png" },
    { name: "Bangladesh", code: "BD", phone: 880, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" },
    { name: "Barbados", code: "BB", phone: 1246, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/23px-Flag_of_Barbados.svg.png" },
    { name: "Belarus", code: "BY", phone: 375, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/23px-Flag_of_Belarus.svg.png" },
    { name: "Belgium", code: "BE", phone: 32, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/23px-Flag_of_Belgium_%28civil%29.svg.png" },
    { name: "Belize", code: "BZ", phone: 501, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/23px-Flag_of_Belize.svg.png" },
    { name: "Benin", code: "BJ", phone: 229, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/23px-Flag_of_Benin.svg.png" },
    { name: "Bhutan", code: "BT", phone: 975, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/23px-Flag_of_Bhutan.svg.png" },
    { name: "Bolivia", code: "BO", phone: 591, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/23px-Flag_of_Bolivia.svg.png" },
    { name: "Bosnia and Herzegovina", code: "BA", phone: 387, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/23px-Flag_of_Bosnia_and_Herzegovina.svg.png" },
    { name: "Botswana", code: "BW", phone: 267, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/23px-Flag_of_Botswana.svg.png" },
    { name: "Brazil", code: "BR", phone: 55, flag: "//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png" },
    { name: "Brunei Darussalam", code: "BN", phone: 673, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/23px-Flag_of_Brunei.svg.png" },
    { name: "Bulgaria", code: "BG", phone: 359, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/23px-Flag_of_Bulgaria.svg.png" },
    { name: "Burkina Faso", code: "BF", phone: 226, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/23px-Flag_of_Burkina_Faso.svg.png" },
    { name: "Burundi", code: "BI", phone: 257, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/23px-Flag_of_Burundi.svg.png" },
    { name: "Cambodia", code: "KH", phone: 855, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/23px-Flag_of_Cambodia.svg.png" },
    { name: "Cameroon", code: "CM", phone: 237, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/23px-Flag_of_Cameroon.svg.png" },
    { name: "Canada", code: "CA", phone: 1, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/23px-Flag_of_Canada.svg.png" },
    { name: "Cape Verde", code: "CV", phone: 238, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/23px-Flag_of_Cape_Verde.svg.png" },
    { name: "Cayman Islands", code: "KY", phone: 1345, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/23px-Flag_of_the_Cayman_Islands.svg.png" },
    { name: "Central African Republic", code: "CF", phone: 236, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/23px-Flag_of_the_Central_African_Republic.svg.png" },
    { name: "Chad", code: "TD", phone: 235, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/23px-Flag_of_Chad.svg.png" },
    { name: "Chile", code: "CL", phone: 56, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/23px-Flag_of_Chile.svg.png" },
    { name: "China", code: "CN", phone: 86, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" },
    { name: "Colombia", code: "CO", phone: 57, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/23px-Flag_of_Colombia.svg.png" },
    { name: "Comoros", code: "KM", phone: 269, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/23px-Flag_of_the_Comoros.svg.png" },
    { name: "Congo", code: "CG", phone: 242, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/23px-Flag_of_the_Republic_of_the_Congo.svg.png" },
    { name: "Cook Islands", code: "CK", phone: 682, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/23px-Flag_of_the_Cook_Islands.svg.png" },
    { name: "Costa Rica", code: "CR", phone: 506, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/23px-Flag_of_Costa_Rica_%28state%29.svg.png" },
    { name: "Croatia", code: "HR", phone: 385, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/23px-Flag_of_Croatia.svg.png" },
    { name: "Cuba", code: "CU", phone: 53, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/23px-Flag_of_Cuba.svg.png" },
    { name: "Cyprus", code: "CY", phone: 357, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/23px-Flag_of_Cyprus.svg.png" },
    { name: "Czech Republic", code: "CZ", phone: 420, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/23px-Flag_of_the_Czech_Republic.svg.png" },
    { name: "Denmark", code: "DK", phone: 45, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png" },
    { name: "Djibouti", code: "DJ", phone: 253, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/23px-Flag_of_Djibouti.svg.png" },
    { name: "Dominican Republic", code: "DO", phone: 1, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/23px-Flag_of_the_Dominican_Republic.svg.png" },
    { name: "Ecuador", code: "EC", phone: 593, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/23px-Flag_of_Ecuador.svg.png" },
    { name: "Egypt", code: "EG", phone: 20, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/23px-Flag_of_Egypt.svg.png" },
    { name: "El Salvador", code: "SV", phone: 503, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/23px-Flag_of_El_Salvador.svg.png" },
    { name: "Equatorial Guinea", code: "GQ", phone: 240, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/23px-Flag_of_Equatorial_Guinea.svg.png" },
    { name: "Eritrea", code: "ER", phone: 291, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/23px-Flag_of_Eritrea.svg.png" },
    { name: "Estonia", code: "EE", phone: 372, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/23px-Flag_of_Estonia.svg.png" },
    { name: "Ethiopia", code: "ET", phone: 251, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/23px-Flag_of_Ethiopia.svg.png" },
    { name: "Faroe Islands", code: "FO", phone: 298, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/21px-Flag_of_the_Faroe_Islands.svg.png" },
    { name: "Fiji", code: "FJ", phone: 679, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/23px-Flag_of_Fiji.svg.png" },
    { name: "Finland", code: "FI", phone: 358, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/23px-Flag_of_Finland.svg.png" },
    { name: "France", code: "FR", phone: 33, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
    { name: "Gabon", code: "GA", phone: 241, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/23px-Flag_of_Gabon.svg.png" },
    { name: "Gambia", code: "GM", phone: 220, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/23px-Flag_of_The_Gambia.svg.png" },
    { name: "Georgia", code: "GE", phone: 995, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/23px-Flag_of_Georgia.svg.png" },
    { name: "Germany", code: "DE", phone: 49, flag: "//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/23px-Flag_of_Germany.svg.png" },
    { name: "Ghana", code: "GH", phone: 233, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/23px-Flag_of_Ghana.svg.png" },
    { name: "Gibraltar", code: "GI", phone: 350, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/23px-Flag_of_Gibraltar.svg.png" },
    { name: "Greece", code: "GR", phone: 30, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png" },
    { name: "Greenland", code: "GL", phone: 299, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/23px-Flag_of_Greenland.svg.png" },
    { name: "Grenada", code: "GD", phone: 1473, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/23px-Flag_of_Grenada.svg.png" },
    { name: "Guadeloupe", code: "GP", phone: 590, flag: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
    { name: "Guam", code: "GU", phone: 1671, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/23px-Flag_of_Guam.svg.png" },
    { name: "Guatemala", code: "GT", phone: 502, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/23px-Flag_of_Guatemala.svg.png" },
    { name: "Guernsey", code: "GG", phone: 44, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/23px-Flag_of_Guernsey.svg.png" },
    { name: "Guinea", code: "GN", phone: 224, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/23px-Flag_of_Guinea.svg.png" },
    { name: "Guinea-Bissau", code: "GW", phone: 245, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/23px-Flag_of_Guinea-Bissau.svg.png" },
    { name: "Guyana", code: "GY", phone: 592, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/23px-Flag_of_Guyana.svg.png" },
    { name: "Haiti", code: "HT", phone: 509, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/23px-Flag_of_Haiti.svg.png" },
    { name: "Honduras", code: "HN", phone: 504, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/23px-Flag_of_Honduras.svg.png" },
    { name: "Hong Kong", code: "HK", phone: 852, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/23px-Flag_of_Hong_Kong.svg.png" },
    { name: "Hungary", code: "HU", phone: 36, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/23px-Flag_of_Hungary.svg.png" },
    { name: "Iceland", code: "IS", phone: 354, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/21px-Flag_of_Iceland.svg.png" },
    { name: "India", code: "IN", phone: 91, flag: "//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" },
    { name: "Indonesia", code: "ID", phone: 62, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png" },
    { name: "Iran", code: "IR", phone: 98, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png" },
    { name: "Iraq", code: "IQ", phone: 964, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/23px-Flag_of_Iraq.svg.png" },
    { name: "Ireland", code: "IE", phone: 353, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/23px-Flag_of_Ireland.svg.png" },
    { name: "Isle of Man", code: "IM", phone: 44, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_the_Isle_of_Man.svg/23px-Flag_of_the_Isle_of_Man.svg.png" },
    { name: "Israel", code: "IL", phone: 972, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/23px-Flag_of_Israel.svg.png" },
    { name: "Italy", code: "IT", phone: 39, flag: "//upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/23px-Flag_of_Italy.svg.png" },
    { name: "Jamaica", code: "JM", phone: 1876, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/23px-Flag_of_Jamaica.svg.png" },
    { name: "Japan", code: "JP", phone: 81, flag: "//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.png" },
    { name: "Jersey", code: "JE", phone: 44, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/23px-Flag_of_Jersey.svg.png" },
    { name: "Jordan", code: "JO", phone: 962, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/23px-Flag_of_Jordan.svg.png" },
    { name: "Kazakhstan", code: "KZ", phone: 7, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/23px-Flag_of_Kazakhstan.svg.png" },
    { name: "Kenya", code: "KE", phone: 254, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/23px-Flag_of_Kenya.svg.png" },
    { name: "Kiribati", code: "KI", phone: 686, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/23px-Flag_of_Kiribati.svg.png" },
    { name: "North Korea", code: "KP", phone: 850, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/23px-Flag_of_North_Korea.svg.png" },
    { name: "South Korea", code: "KR", phone: 82, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png" },
    { name: "Kosovo", code: "XK", phone: 383, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Kosovo.svg/23px-Flag_of_Kosovo.svg.png" },
    { name: "Kuwait", code: "KW", phone: 965, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/23px-Flag_of_Kuwait.svg.png" },
    { name: "Kyrgyzstan", code: "KG", phone: 996, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/23px-Flag_of_Kyrgyzstan.svg.png" },
    { name: "Laos", code: "LA", phone: 856, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/23px-Flag_of_Laos.svg.png" },
    { name: "Latvia", code: "LV", phone: 371, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/23px-Flag_of_Latvia.svg.png" },
    { name: "Lebanon", code: "LB", phone: 961, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/23px-Flag_of_Lebanon.svg.png" },
    { name: "Lesotho", code: "LS", phone: 266, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/23px-Flag_of_Lesotho.svg.png" },
    { name: "Liberia", code: "LR", phone: 231, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/23px-Flag_of_Liberia.svg.png" },
    { name: "Libya", code: "LY", phone: 218, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/23px-Flag_of_Libya.svg.png" },
    { name: "Liechtenstein", code: "LI", phone: 423, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/20px-Flag_of_Liechtenstein.svg.png" },
    { name: "Lithuania", code: "LT", phone: 370, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/23px-Flag_of_Lithuania.svg.png" },
    { name: "Luxembourg", code: "LU", phone: 352, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/23px-Flag_of_Luxembourg.svg.png" },
    { name: "Macao", code: "MO", phone: 853, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/23px-Flag_of_Macau.svg.png" },
    { name: "Macedonia", code: "MK", phone: 389, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/23px-Flag_of_North_Macedonia.svg.png" },
    { name: "Madagascar", code: "MG", phone: 261, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/23px-Flag_of_Madagascar.svg.png" },
    { name: "Malawi", code: "MW", phone: 265, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/23px-Flag_of_Malawi.svg.png" },
    { name: "Malaysia", code: "MY", phone: 60, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/23px-Flag_of_Malaysia.svg.png" },
    { name: "Maldives", code: "MV", phone: 960, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/23px-Flag_of_Maldives.svg.png" },
    { name: "Mali", code: "ML", phone: 223, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/23px-Flag_of_Mali.svg.png" },
    { name: "Malta", code: "MT", phone: 356, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/23px-Flag_of_Malta.svg.png" },
    { name: "Martinique", code: "MQ", phone: 596, flag: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png" },
    { name: "Mauritania", code: "MR", phone: 222, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/23px-Flag_of_Mauritania.svg.png" },
    { name: "Mauritius", code: "MU", phone: 230, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/23px-Flag_of_Mauritius.svg.png" },
    { name: "Mexico", code: "MX", phone: 52, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.png" },
    { name: "Moldova", code: "MD", phone: 373, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/23px-Flag_of_Moldova.svg.png" },
    { name: "Monaco", code: "MC", phone: 377, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/23px-Flag_of_Monaco.svg.png" },
    { name: "Mongolia", code: "MN", phone: 976, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/23px-Flag_of_Mongolia.svg.png" },
    { name: "Montenegro", code: "ME", phone: 382, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/23px-Flag_of_Montenegro.svg.png" },
    { name: "Morocco", code: "MA", phone: 212, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/23px-Flag_of_Morocco.svg.png" },
    { name: "Mozambique", code: "MZ", phone: 258, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/23px-Flag_of_Mozambique.svg.png" },
    { name: "Myanmar", code: "MM", phone: 95, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/23px-Flag_of_Myanmar.svg.png" },
    { name: "Namibia", code: "NA", phone: 264, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/23px-Flag_of_Namibia.svg.png" },
    { name: "Nauru", code: "NR", phone: 674, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/23px-Flag_of_Nauru.svg.png" },
    { name: "Nepal", code: "NP", phone: 977, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/23px-Flag_of_Nepal.svg.png" },
    { name: "Netherlands", code: "NL", phone: 31, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png" },
    { name: "New Caledonia", code: "NC", phone: 687, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/43px-Flags_of_New_Caledonia.svg.png" },
    { name: "New Zealand", code: "NZ", phone: 64, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/23px-Flag_of_New_Zealand.svg.png" },
    { name: "Nicaragua", code: "NI", phone: 505, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/23px-Flag_of_Nicaragua.svg.png" },
    { name: "Niger", code: "NE", phone: 227, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/23px-Flag_of_Niger.svg.png" },
    { name: "Nigeria", code: "NG", phone: 234, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.png" },
    { name: "Niue", code: "NU", phone: 683, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/23px-Flag_of_Niue.svg.png" },
    { name: "Norfolk Island", code: "NF", phone: 672, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/23px-Flag_of_Norfolk_Island.svg.png" },
    { name: "Northern Mariana Islands", code: "MP", phone: 1670, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/23px-Flag_of_the_Northern_Mariana_Islands.svg.png" },
    { name: "Norway", code: "NO", phone: 47, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.png" },
    { name: "Oman", code: "OM", phone: 968, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/23px-Flag_of_Oman.svg.png" },
    { name: "Pakistan", code: "PK", phone: 92, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.png" },
    { name: "Palau", code: "PW", phone: 680, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/23px-Flag_of_Palau.svg.png" },
    { name: "Palestine", code: "PS", phone: 970, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/23px-Flag_of_Palestine.svg.png" },
    { name: "Panama", code: "PA", phone: 507, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/23px-Flag_of_Panama.svg.png" },
    { name: "Papua New Guinea", code: "PG", phone: 675, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/23px-Flag_of_Papua_New_Guinea.svg.png" },
    { name: "Paraguay", code: "PY", phone: 595, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/23px-Flag_of_Paraguay.svg.png" },
    { name: "Peru", code: "PE", phone: 51, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/23px-Flag_of_Peru.svg.png" },
    { name: "Philippines", code: "PH", phone: 63, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/23px-Flag_of_the_Philippines.svg.png" },
    { name: "Pitcairn", code: "PN", phone: 64, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/23px-Flag_of_the_Pitcairn_Islands.svg.png" },
    { name: "Poland", code: "PL", phone: 48, flag: "//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.png" },
    { name: "Portugal", code: "PT", phone: 351, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/23px-Flag_of_Portugal.svg.png" },
    { name: "Puerto Rico", code: "PR", phone: 1787, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/23px-Flag_of_Puerto_Rico.svg.png" },
    { name: "Qatar", code: "QA", phone: 974, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/23px-Flag_of_Qatar.svg.png" },
    { name: "Romania", code: "RO", phone: 40, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png" },
    { name: "Russian Federation", code: "RU", phone: 7, flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.png" },
    { name: "Rwanda", code: "RW", phone: 250, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/23px-Flag_of_Rwanda.svg.png" },
    { name: "Samoa", code: "WS", phone: 684, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/23px-Flag_of_Samoa.svg.png" },
    { name: "San Marino", code: "SM", phone: 378, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/23px-Flag_of_San_Marino.svg.png" },
    { name: "Sao Tome and Principe", code: "ST", phone: 239, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg/23px-Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg.png" },
    { name: "Saudi Arabia", code: "SA", phone: 966, flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.png" },
    { name: "Serbia", code: "RS", phone: 381, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/23px-Flag_of_Serbia.svg.png" },
    { name: "Seychelles", code: "SC", phone: 248, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/23px-Flag_of_Seychelles.svg.png" },
    { name: "Sierra Leone", code: "SL", phone: 232, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/23px-Flag_of_Sierra_Leone.svg.png" },
    { name: "Singapore", code: "SG", phone: 65, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png" },
    { name: "Slovakia", code: "SK", phone: 421, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/23px-Flag_of_Slovakia.svg.png" },
    { name: "Slovenia", code: "SI", phone: 386, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/23px-Flag_of_Slovenia.svg.png" },
    { name: "Somalia", code: "SO", phone: 252, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/23px-Flag_of_Somalia.svg.png" },
    { name: "South Africa", code: "ZA", phone: 27, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/23px-Flag_of_South_Africa.svg.png" },
    { name: "South Sudan", code: "SS", phone: 211, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/23px-Flag_of_South_Sudan.svg.png" },
    { name: "Spain", code: "ES", phone: 34, flag: "//upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/23px-Flag_of_Spain.svg.png" },
    { name: "Sri Lanka", code: "LK", phone: 94, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/23px-Flag_of_Sri_Lanka.svg.png" },
    { name: "Sudan", code: "SD", phone: 249, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/23px-Flag_of_Sudan.svg.png" },
    { name: "Suriname", code: "SR", phone: 597, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/23px-Flag_of_Suriname.svg.png" },
    { name: "Sweden", code: "SE", phone: 46, flag: "//upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/23px-Flag_of_Sweden.svg.png" },
    { name: "Switzerland", code: "CH", phone: 41, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png" },
    { name: "Taiwan", code: "TW", phone: 886, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png" },
    { name: "Tajikistan", code: "TJ", phone: 992, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/23px-Flag_of_Tajikistan.svg.png" },
    { name: "Tanzania", code: "TZ", phone: 255, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/23px-Flag_of_Tanzania.svg.png" },
    { name: "Thailand", code: "TH", phone: 66, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/23px-Flag_of_Thailand.svg.png" },
    { name: "Togo", code: "TG", phone: 228, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/23px-Flag_of_Togo.svg.png" },
    { name: "Tokelau", code: "TK", phone: 690, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/23px-Flag_of_Tokelau.svg.png" },
    { name: "Tonga", code: "TO", phone: 676, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/23px-Flag_of_Tonga.svg.png" },
    { name: "Trinidad and Tobago", code: "TT", phone: 1868, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/23px-Flag_of_Trinidad_and_Tobago.svg.png" },
    { name: "Tunisia", code: "TN", phone: 216, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/23px-Flag_of_Tunisia.svg.png" },
    { name: "Turkey", code: "TR", phone: 90, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.png" },
    { name: "Uganda", code: "UG", phone: 256, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/23px-Flag_of_Uganda.svg.png" },
    { name: "Ukraine", code: "UA", phone: 380, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/23px-Flag_of_Ukraine.svg.png" },
    { name: "United Arab Emirates", code: "AE", phone: 971, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/23px-Flag_of_the_United_Arab_Emirates.svg.png" },
    { name: "United Kingdom", code: "GB", phone: 44, flag: "//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png" },
    { name: "United States of America", code: "US", phone: 1, flag: "//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" },
    { name: "Uruguay", code: "UY", phone: 598, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/23px-Flag_of_Uruguay.svg.png" },
    { name: "Uzbekistan", code: "UZ", phone: 998, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/23px-Flag_of_Uzbekistan.svg.png" },
    { name: "Vanuatu", code: "VU", phone: 678, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/23px-Flag_of_Vanuatu.svg.png" },
    { name: "Venezuela (Bolivarian Republic of)", code: "VE", phone: 58, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/23px-Flag_of_Venezuela.svg.png" },
    { name: "Viet Nam", code: "VN", phone: 84, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/23px-Flag_of_Vietnam.svg.png" },
    { name: "Yemen", code: "YE", phone: 967, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/23px-Flag_of_Yemen.svg.png" },
    { name: "Zambia", code: "ZM", phone: 260, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/23px-Flag_of_Zambia.svg.png" },
    { name: "Zimbabwe", code: "ZW", phone: 263, flag: "//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/23px-Flag_of_Zimbabwe.svg.png" }
];

export default countries;